version: "3"
services:
  mysql:
    image: marmotjs/marmot-mysql
    restart: always
    volumes:
      - $HOME/marmot_home/mysql_data:/var/lib/mysql
  web:
    image: marmotjs/marmot-web
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "80:9900"
    environment:
      - MYSQL_HOST=mysql
      - MARMOT_HOST=127.0.0.1 # replace it with your hostname: MARMOT_HOST=example.com
      - MARMOT_PORT=80        # keep the same as ports' left number
  nginx:
    image: marmotjs/marmot-nginx
    restart: always
    volumes:
      - $HOME/marmot_home/static:/usr/share/nginx/html:ro
    ports:
      - "9920:80"
